apiVersion: v1
kind: Service
metadata:
  name: flight-app-service
  namespace: flight-app-dev
spec:
  selector:
    app: flight-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
