apiVersion: apps/v1
kind: Deployment

metadata:
  name: flight-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: flight-app

  template:
    metadata:
      labels:
        app: flight-app

    spec:
      containers:
        - name: flight-app
          image: filosoho/flight-app

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: flight-app-config

            - secretRef:
                name: flight-app-secret

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
