apiVersion: v1
kind: Secret
metadata:
  name: flight-app-secret
  namespace: flight-app-dev

type: Opaque
stringData:
  SECRET_KEY: "618b0a2b49228d1cd349d937184328d571fc74e6e6b7317d28a234b21d669f11"
  DB_PASSWORD: "password"
