apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flight-app-dev

resources:
  - ../../base
  - namespace.yaml
  - flight-app-config.yaml
  - flight-app-secret.yaml
  - postgres-secret.yaml

images:
  - name: filosoho/flight-app
    newTag: 0.1.3
